### ISSUE TITLE
Edits for GITHUBING.md

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-identity#28]
Hi @meker12: Rather than edit the file and create a PR, I marked up a Word doc. I am attaching it, plus a PDF copy of it (in case you'd rather look at the PDF). I had some questions and wasn't sure about a few suggestions, so I'd rather you implement the changes. If you have any questions, please let me know. Thanks!

[GitHub workflow_editsKH.pdf](https://github.com/rackerlabs/docs-cloud-identity/files/131433/GitHub.workflow_editsKH.pdf)
[GitHub workflow_editsKH.docx](https://github.com/rackerlabs/docs-cloud-identity/files/131434/GitHub.workflow_editsKH.docx)

**Comment by meker12** [comment]
Thanks @kmsholcomb!  I'll add the review instructions after we finalize them, and then we can propagate these contributor files to other repos.

**Comment by meker12** [comment]
Completed with PR #30.
