### ISSUE TITLE
API docs for Add/Update tenant endpoints

### ISSUE THREAD

**Issue by malini-kamalambal** [rackerlabs/docs-cloud-identity#48]
Update the docs to include "display-name" in the list of fields for the request.
See sample here https://github.rackspace.com/ServiceAPIContracts/global-auth-keystone-extensions/blob/master/src/formattedsamples/TenantWithDomainId.json

**Comment by meker12** [comment]
Included this in the "list tenants" operation in the public docs.  

Also need to add to [docs-cloud-identity-admin docs](https://github.com/rackerlabs/docs-cloud-identity-admin)

**Comment by meker12** [comment]
Display name was added to public docs.

Separate Issue for update to admin docs at https://github.com/rackerlabs/docs-cloud-identity/blob/master/api-docs/api-reference/methods/tenants/get-list-tenants-v2.0.rst.

Closing this one.
