### ISSUE TITLE
'list services' call does not support 'name' query parameter

### ISSUE THREAD

**Issue by bhushan5** [rackerlabs/docs-cloud-identity#7]
The documentation for list services call shows 'name' as a valid query parameter :
http://docs-internal.rackspace.com/auth/api/v2.0/auth-admin-devguide/content/GET_listServices__v2.0_OS-KSADM_services__Service_Calls.html

But, as confirmed with the devs, this call does not support that particular query parameter.

**Comment by meker12** [comment]
This issue was moved to rackerlabs/docs-cloud-identity-admin#5
